### PR TITLE
fix(homepage): date typo

### PR DESCRIPTION
**Pull request by n1c01a5**
2018 -> 2019

### CODE REVIEW

**Comment by jdetychey** [comment]
en prod!

**Comment by jdetychey** [comment]
may have merged this a bit too quickly. The **EthCC 2018** button was intended to lead to the 2018 webpage. It's now a **EthCC 2019** button leading to the 2018 page. Isn't it a little confusion @n1c01a5  ?

**Comment by n1c01a5** [comment]
Yes sorry. Maybe we can link this button to https://blockchainweek.fr/.

**Comment by n1c01a5** [comment]
yes indeed

**Pull request merged**
